mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls'), name = 'index' ),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls")),
     path("", TemplateView.as_view(template_name="home.html"), name="home"),
    
]

user_auth/urls.py
from django.urls import path
from . import views

# provide app name
app_name = 'user_auth'


urlpatterns = [

    path('login', views.user_login, name="login"),
    path('logout_user', views.logout_user, name='logout'),
    #path('authenticate_user/', views.authenticate, name='authenticate_user'),
    path('register_user/', views.register_user, name='register_user'),
   

]

website/urls.py
from django.urls import path
from . import views

# provide app name
app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/',views.shop, name = 'shop'),
    path('aboutus/', views.about_us, name='about_us'),
    path('contactus/', views.contact, name = 'contact_us'),   
]

user_auth/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models

# Create your models here.

user_auth/forms.py
# information to create registration form found on https://ordinarycoders.com/blog/article/django-user-register-login-logout

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class RegisterUserForm(UserCreationForm):
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
	

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


	def __init__(self, *args, **kwargs):
		super(RegisterUserForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['class'] = 'form-control'

user_auth/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm
from django.urls import reverse





def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.success(request, ("There Was An Error Logging In, Try Again..."))
            return redirect('login')
    else:
        return render(request, 'user_auth/login.html', {})







def logout_user(request):
    logout(request)
    messages.success(request, "You Were Logged Out!")
    return redirect('home')


def register_user(request):
	if request.method == "POST":
		form = RegisterUserForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(username=username, password=password)
			login(request, user)
			messages.success(request, ("Registration Successful!"))
			return redirect('home')
	else:
		form = RegisterUserForm()

	return render(request, 'user_auth/register_user.html', {
		'form':form,
		})




# def authenticate_user(request):
#     """
#     Function is used to authenticate the user.

#     :param request: data input from the website received via request

#     :return: directs user to appropriate page (if user is not found == register new user page; if user authenticated == home page)
#     """
#     username = request.POST['username']
#     password = request.POST['password']
#     user = authenticate(username=username, password=password)

#     if user is None:
#         return HttpResponseRedirect(reverse('user_auth:register_user'))
#     else:
#         login(request,user)
#         return HttpResponseRedirect(reverse('website:home'))
	


    

website/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Views used to direct user to relevant page

def home(request):
    """
    Function directs user to homepage
    """
    return render(request,'website/index.html')

def about_us(request):
    """
    Function directs user to about us page
    """
    return render(request,'website/about_us.html')

def shop(request):
    """
    Function directs user to shop page
    """
    return render(request,'website/shop.html')

def contact(request):
    """
    Function directs user to contact us page
    """
    return render(request,'website/contact_us.html')

user_auth/templates/user_auth/base.html
{% load static %}
<!DOCTYPE html>

<html lang = 'eng'>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale = 1.0">
        <!-- import bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

        <!-- allow pdf import -->
        <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.7.570/build/pdf.min.js"></script>

        <!-- import stylesheet -->
        <link rel = 'stylesheet'  href = "{%static 'stylesheet.css' %}">
        <!-- import icons -->
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    </head>

    <body>

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you set up the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}






{% comment %} <!-- base.html -->

{% load static %}

<!DOCTYPE html>

<html lang = 'eng'>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale = 1.0">
        <!-- import bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

        <!-- allow pdf import -->
        <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.7.570/build/pdf.min.js"></script>

        <!-- import stylesheet -->
        <link rel = 'stylesheet'  href = "{%static 'stylesheet.css' %}">
        <!-- import icons -->
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    </head>

    <body>
      <div class = "row">
            {% if user.is_authenticated %}
            <!-- navbar 2 (user logged in) -->
            <nav class="navbar navbar-expand-lg navbar-light bg-light gradient-custom fixed-top">
              <!-- Container wrapper start -->
              <div class="container-fluid">
                  <!-- Toggle button start -->
                  <button
                    class="navbar-toggler"
                    type="button"
                    data-mdb-toggle="collapse"
                    data-mdb-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                  >
                    <i class="fas fa-bars"></i>
                  </button>
                  <!-- Toggle button end -->

                  <!-- Collapsible wrapper start -->
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Navbar brand -->
                    <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'website:home' %}">
                      <img
                        src="{% static 'website/logo.png' %}" 
                        height="100"
                        alt="Company Logo"
                        loading="lazy"
                      />
                    </a>
                    <!-- Left links start -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 h3">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:about_us' %}">About Us</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:shop' %}">Shop</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:contact_us' %}">Contact Us</a>
                      </li>
                     
                    <!-- Left links end -->
                    <!-- Right elements start -->
                    <div class = "navbar-nav">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAccount" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img 
                          class="avatar avatar-32 bg-light rounded-circle text-white p-2"
                          src="https://raw.githubusercontent.com/twbs/icons/main/icons/person-fill.svg">
                      </a>
                      
                      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownAccount">
                        <h5>{{ user.get_username }}</h5>
                        <li class="nav-item dropdown">
                          <a class="dropdown-item" href="{% url 'user_auth:logout' %}">Logout</a>
                        </li>
                      </ul>
                      
                    </div>
                    <!-- Right elements end -->
                  </div>
                  <!-- Collapsible wrapper end -->
            

                
              </div>
              <!-- Container wrapper end -->
            </nav>

            {% else %}
                <!-- navbar 1 (user not logged in) -->
                <nav class="navbar navbar-expand-lg navbar-light bg-light gradient-custom fixed-top ">
                    <!-- Container wrapper -->
                    <div class="container-fluid">
                      <!-- Toggle button -->
                      <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                      >
                        <i class="fas fa-bars"></i>
                      </button>
                  
                      <!-- Collapsible wrapper -->
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Navbar brand -->
                        <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'website:home' %}">
                          <img
                            src="{% static 'website/logo.png' %}" 
                            height="100"
                            alt="Company Logo"
                            loading="lazy"
                          />
                        </a>
                        <!-- Left links -->
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 h3">
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'website:about_us' %}">About Us</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'website:shop' %}">Shop</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'website:contact_us' %}">Contact Us</a>
                          </li>
                         
                        </ul>
                        <!-- Left links -->
                      </div>
                      <!-- Collapsible wrapper -->
                  
                      <!-- Right elements -->
                      <div class="d-flex align-items-center">
                          <ul class="navbar-nav me-auto mb-2 mb-lg-0 navbar-dark">
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'user_auth:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'user_auth:register_user' %}">Register</a>
                            </li>
                          </ul>
                        
                      </div>
                      <!-- Right elements -->
                    </div>
                    <!-- Container wrapper -->
                  </nav>

              {% endif %}
      </div>
      <br><br><br><br><br><br>
      <div class = "row">
          {% block main %}{% endblock %}
      </div>

    </body>
</html> {% endcomment %}

user_auth/templates/user_auth/login.html
{% extends 'user_auth/base.html' %}
{% load static %}

{% block content %}
    
    <h1 class="login-heading">Login</h1>
    <br/>

    <form action="" method="POST">
        {% csrf_token %}

        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Username</label>
            <input type="text" class="form-control" name="username" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control" name="password">
        </div>

        <input type="submit" value="Submit" class="btn btn-secondary">
        

    </form>

    <br/><br/>

{% endblock %}



{% comment %} 
{% extends 'user_auth/base.html' %}
{% load static %} {% endcomment %}
{% comment %} 
{% block content %}
	
	<h1>Login</h1>
<br/>

		<form action="" method=POST>
			{% csrf_token %}

		<form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Username</label>
    <input type="text" class="form-control" name="username" aria-describedby="emailHelp">
    
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" name="password">
  </div>

			<input type="submit" value="Submit" class="btn btn-secondary">

		</form>
		

<br/><br/>	
{% endblock %} {% endcomment %}

user_auth/templates/user_auth/register_user.html
{% extends 'user_auth/base.html' %}
{% load static %}
{% block content %}

{% if form.errors %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    There was an error with your form...
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<div class="shadow p-4 mb-5 bg-body rounded">
    <h1>Register</h1>
    <br/>

    <form method="post" action="{% url 'user_auth:register_user' %}">
        {% csrf_token %}

        {{ form.as_p }}

        <br/><br/>
        <input type="submit" value="Submit" class="btn btn-secondary">
    </form>
</div>
<br/><br/>
{% endblock %}

website/templates/website/about_us.html
<!-- about_us.html -->
{% extends 'website/base.html' %}
{% load static %}
{% block title%}About Us{% endblock %}
{% block main %}
<div class = "row">
    <div class = "col-lg-1"></div>
    <div class = "col-lg-6 gradient-custom text-white">
        <div class="row">
            <h1>About Us</h1>
            <p>We provide a valuable service by giving shoppers access to fresh flowers online that can be delivered just <br>
                about anywhere, quickly and simply. Our large network of professional florists and specially picked <br>
                flower shops allows us to ensure that we deliver the best locally and globally. Working from their florist <br>
                shops, our creative professionals offer up sublime blooms, arrangements and hampers that are <br>suitable for any occasion you can imagine. The flower shops we partner with buy fresh from the best
                 <br>growers and markets, ensuring that we're always a cut above the rest - and at unbeatable prices too..</p>
        </div>
        <br>
        <div class="row">
            <h1>Our Team</h1>
           <img src = "{% static 'website/team1.jpg' %}" class="rounded">
            <p>Emma Oliver - Floral designer</p>
            <p>I’m the founder of belissimo and my job is to make sure the shop grows in a sustainable, exciting way. My specialist sectors are financial and professional services and I’m good at making sure clients buy into the vision of where their brand could go, coming up with creative ideas and inspiring the team to achieve bigger and better things.</p>

        </div>
        <div class="row">
           
            <img src = "{% static 'website/team2.jpg' %}" class="rounded">
            <p>Amelia Mark  - Customer service or sales representative </p>
            <p>I am in charge of the day-to-day operational running of the business, which includes our business strategy, operations and client services.  Over the past 10 years I’ve transformed the way that we measure and report on what we do for our clients </p>
        </div>
        <div class="row">
           
            <img src = "{% static 'website/team3.jpg' %}"  class="rounded">
            <p>Sophia Rich - Spray Maker</p>
            <p>I’m responsible for maintaining the quality and standard of belissimo  flowers as well as the agency’s HR, learning and development.</p>
        </div>
    </div>
     <!-- copyright section start -->
     
    <div class = "col-lg-5"></div>
</div>
<br><div class = "row"></div><br>

<!-- templates/footer.html -->
<footer>
    <p class="copyright">2023 All Rights Reserved. </p>
</footer>

 

{% endblock %}

website/templates/website/base.html
<!-- base.html -->

{% load static %}

<!DOCTYPE html>

<html lang = 'eng'>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale = 1.0">
        <!-- import bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <!-- import bootstrap avatar icon -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-avatar@latest/dist/avatar.min.css" rel="stylesheet">
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">

        <!-- allow pdf import -->
        <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.7.570/build/pdf.min.js"></script>
        <!-- import stylesheet -->
        <link rel = 'stylesheet'  href = "{% static 'stylesheet.css' %}">
        <!-- import icons -->

    </head>

    <body>
      <div class = "row">
            {% if user.is_authenticated %}
            <!-- navbar 2 (user logged in) -->
            <nav class="navbar navbar-expand-lg navbar-light bg-light gradient-custom fixed-top">
              <!-- Container wrapper start -->
              <div class="container-fluid">
                  <!-- Toggle button start -->
                  <button
                    class="navbar-toggler"
                    type="button"
                    data-mdb-toggle="collapse"
                    data-mdb-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                  >
                    <i class="fas fa-bars">
                      <a href="{% url 'website:about_us' %}">About Us</a>

                      <!-- "Contact" button with custom style -->
                          <a href="{% url 'website:contact_us' %}">Contact Us</a>
      
                              <!-- "Shop" button with custom style -->
                          <a href="{% url 'website:shop' %}">Shop</a>
      
      





                    </i>
                  </button>
                 

                  <!-- Toggle button end -->

                  <!-- Collapsible wrapper start -->
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Navbar brand -->
                    <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'website:home' %}">
                      <img
                        src="{% static 'website/logo.png/' %}" 
                        height="100"
                        alt="Company Logo"
                        loading="lazy"
                      />
                    </a>
                    <!-- Left links start -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 h3">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:about_us' %}">About Us</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:shop' %}">Shop</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:contact_us' %}">Contact Us</a>
                      </li>
                      
                    </ul>
                    <!-- Left links end -->
                    <!-- Right elements start -->
                    <div class = "navbar-nav">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAccount" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img 
                          class="avatar avatar-32 bg-light rounded-circle text-white p-2"
                          src="https://raw.githubusercontent.com/twbs/icons/main/icons/person-fill.svg">
                      </a>
                      
                      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownAccount">
                        <h5>{{ user.get_username }}</h5>
                        <li class="nav-item dropdown">
                          <a class="dropdown-item" href="{% url 'user_auth:logout' %}">Logout</a>
                          <a class="dropdown-item" href="{% url 'user_auth:login' %}">Login</a>
                          <a class="dropdown-item" href="{% url 'user_auth:register_user' %}">Register_user</a>
                        </li>
                      </ul>
                      
                    </div>
                    <!-- Right elements end -->
                  </div>
                  <!-- Collapsible wrapper end -->
            

                
              </div>
              <!-- Container wrapper end -->
            </nav>

            {% else %}
                <!-- navbar 1 (user not logged in) -->
                <nav class="navbar navbar-expand-lg navbar-light bg-light gradient-custom fixed-top">
                    <!-- Container wrapper -->
                    <div class="container-fluid">
                      <!-- Toggle button -->
                      <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                      >
                        <i class="fas fa-bars"></i>
                      </button>
                  
                      <!-- Collapsible wrapper -->
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Navbar brand -->
                        <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'website:home' %}">
                          <img
                            src="{% static 'website/logo.png' %}" 
                            height="100"
                            alt="Company Logo"
                            loading="lazy"
                          />
                        </a>
                        <!-- Left links -->
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 h3">
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'website:about_us' %}">About Us</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'website:shop' %}">Shop</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'website:contact_us' %}">Contact Us</a>
                          </li>
                          
                        </ul>
                        <!-- Left links -->
                      </div>
                      <!-- Collapsible wrapper -->
                  
                      <!-- Right elements -->
                      <div class="d-flex align-items-center">
                          <ul class="navbar-nav me-auto mb-2 mb-lg-0 navbar-dark">
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'user_auth:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'user_auth:register_user' %}">Register</a>
                            </li>
                          </ul>
                        
                 
                      </div>
                      <!-- Right elements -->
                    </div>
                    <!-- Container wrapper -->
                  </nav>

              {% endif %}
      </div>
      
      <br><br><br><br><br><br>
      <div class = "row">
       
      
          {% block main %}{% endblock %}
      </div>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <!-- bootstrap icons -->
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    </body>
</html>